"""Canonical enums and constants."""

from enum import Enum


class PublicLabel(str, Enum):
    UP = "UP"
    FLAT = "FLAT"
    DOWN = "DOWN"


class InternalState(str, Enum):
    CLASSIFIABLE = "CLASSIFIABLE"
    UNCLASSIFIABLE = "UNCLASSIFIABLE"


class TransitionState(str, Enum):
    STABLE = "stable"
    PENDING_UPGRADE = "pending_upgrade"
    PENDING_DOWNGRADE = "pending_downgrade"
    FORCED_FLAT = "forced_flat"
    FAST_TRACK = "fast_track"


class ReasonCode(str, Enum):
    GATE_HISTORY_WEEKLY = "GATE_HISTORY_WEEKLY"
    GATE_HISTORY_DAILY = "GATE_HISTORY_DAILY"
    GATE_HISTORY_HOURLY = "GATE_HISTORY_HOURLY"
    GATE_MISSING_BARS = "GATE_MISSING_BARS"
    GATE_LIQUIDITY = "GATE_LIQUIDITY"
    GATE_BAD_CANDLE = "GATE_BAD_CANDLE"
    GATE_STALE_DATA = "GATE_STALE_DATA"
    NUMERIC_INVALID = "NUMERIC_INVALID"
    MISSING_INTERMEDIATE_LOAD_BEARING = "MISSING_INTERMEDIATE_LOAD_BEARING"
    REALIZED_VOL_INSUFFICIENT = "REALIZED_VOL_INSUFFICIENT"
    ACCEPTANCE_PARTIAL = "ACCEPTANCE_PARTIAL"
    DIAGNOSTIC_MISSING = "DIAGNOSTIC_MISSING"
    CONFLICT_MAJOR = "CONFLICT_MAJOR"
    CONFLICT_SCORE = "CONFLICT_SCORE"
    CONFLICT_QUALITY = "CONFLICT_QUALITY"
    VETO_SHOCK = "VETO_SHOCK"
    VETO_VOLATILITY = "VETO_VOLATILITY"
    VETO_ANOMALY = "VETO_ANOMALY"
    VETO_LIQUIDITY = "VETO_LIQUIDITY"
    VETO_ROLL = "VETO_ROLL"
    TRANSITION_PENDING_UPGRADE = "TRANSITION_PENDING_UPGRADE"
    TRANSITION_PENDING_DOWNGRADE = "TRANSITION_PENDING_DOWNGRADE"
    TRANSITION_FORCED_FLAT = "TRANSITION_FORCED_FLAT"
    RUNTIME_SCHEMA_VALIDATION_FAILED = "RUNTIME_SCHEMA_VALIDATION_FAILED"
    RUNTIME_STATE_PERSIST_FAILED = "RUNTIME_STATE_PERSIST_FAILED"
    RUNTIME_LOG_WRITE_FAILED = "RUNTIME_LOG_WRITE_FAILED"
    RUNTIME_PREVIOUS_STATE_LOCK_FAILED = "RUNTIME_PREVIOUS_STATE_LOCK_FAILED"
