from __future__ import annotations

SPEC_IDENTIFIER = "options-construction-engine-locked-specification"
IMPLEMENTATION_VERSION = "options-construction-engine-v1.1"

FAMILY_BULL_CALL_SPREAD = "BULL_CALL_SPREAD"
FAMILY_BEAR_PUT_SPREAD = "BEAR_PUT_SPREAD"
FAMILY_BULL_PUT_SPREAD = "BULL_PUT_SPREAD"
FAMILY_BEAR_CALL_SPREAD = "BEAR_CALL_SPREAD"
FAMILY_IRON_CONDOR = "IRON_CONDOR"
SUPPORTED_FAMILIES = [
    FAMILY_BULL_CALL_SPREAD,
    FAMILY_BEAR_PUT_SPREAD,
    FAMILY_BULL_PUT_SPREAD,
    FAMILY_BEAR_CALL_SPREAD,
    FAMILY_IRON_CONDOR,
]

CONTRACT_NEAR_MONTH = "NEAR_MONTH"
CONTRACT_NEXT_MONTH = "NEXT_MONTH"
SUPPORTED_CONTRACT_MONTHS = [CONTRACT_NEAR_MONTH, CONTRACT_NEXT_MONTH]

OPTION_CE = "CE"
OPTION_PE = "PE"
SIDE_BUY = "BUY"
SIDE_SELL = "SELL"

ROLE_LONG_LEG = "LONG_LEG"
ROLE_SHORT_LEG = "SHORT_LEG"
ROLE_PUT_LONG_WING = "PUT_LONG_WING"
ROLE_PUT_SHORT = "PUT_SHORT"
ROLE_CALL_SHORT = "CALL_SHORT"
ROLE_CALL_LONG_WING = "CALL_LONG_WING"

STATUS_CONSTRUCTED = "CONSTRUCTED"
STATUS_REJECTED = "REJECTED"

MODE_DELTA = "DELTA"
MODE_DISTANCE = "DISTANCE"

INPUT_MISSING_INSTRUMENT = "INPUT_MISSING_INSTRUMENT"
INPUT_INVALID_ASOF_TIME = "INPUT_INVALID_ASOF_TIME"
INPUT_INVALID_STRATEGY_FAMILY = "INPUT_INVALID_STRATEGY_FAMILY"
INPUT_INVALID_CONTRACT_MONTH = "INPUT_INVALID_CONTRACT_MONTH"
INPUT_INVALID_STRENGTH = "INPUT_INVALID_STRENGTH"
INPUT_INVALID_SPOT = "INPUT_INVALID_SPOT"
INPUT_INVALID_LOT_SIZE = "INPUT_INVALID_LOT_SIZE"
INPUT_INVALID_STRIKE_STEP = "INPUT_INVALID_STRIKE_STEP"

OPTION_CHAIN_MISSING = "OPTION_CHAIN_MISSING"
OPTION_CHAIN_STALE = "OPTION_CHAIN_STALE"
BROKER_INSTRUMENT_NOT_FOUND = "BROKER_INSTRUMENT_NOT_FOUND"
UNDERLYING_MISMATCH = "UNDERLYING_MISMATCH"
EXPIRY_MISMATCH = "EXPIRY_MISMATCH"
LOT_SIZE_MISMATCH = "LOT_SIZE_MISMATCH"

EXPIRY_SELECTED_NEAR_MONTH = "EXPIRY_SELECTED_NEAR_MONTH"
EXPIRY_SELECTED_NEXT_MONTH = "EXPIRY_SELECTED_NEXT_MONTH"
NO_VALID_NEAR_EXPIRY = "NO_VALID_NEAR_EXPIRY"
NO_VALID_NEXT_EXPIRY = "NO_VALID_NEXT_EXPIRY"

DELTA_BASED_STRIKE_SELECTION = "DELTA_BASED_STRIKE_SELECTION"
DISTANCE_BASED_STRIKE_SELECTION = "DISTANCE_BASED_STRIKE_SELECTION"
NO_VALID_STRIKE_PAIR = "NO_VALID_STRIKE_PAIR"

LIQUIDITY_CHECK_PASSED = "LIQUIDITY_CHECK_PASSED"
LIQUIDITY_CHECK_FAILED = "LIQUIDITY_CHECK_FAILED"
BID_ASK_SPREAD_TOO_WIDE = "BID_ASK_SPREAD_TOO_WIDE"
OPEN_INTEREST_TOO_LOW = "OPEN_INTEREST_TOO_LOW"
VOLUME_TOO_LOW = "VOLUME_TOO_LOW"

PREMIUM_CHECK_PASSED = "PREMIUM_CHECK_PASSED"
CREDIT_TOO_LOW = "CREDIT_TOO_LOW"
POOR_REWARD_RISK = "POOR_REWARD_RISK"
INVALID_MAX_LOSS = "INVALID_MAX_LOSS"
INVALID_NET_PREMIUM = "INVALID_NET_PREMIUM"

OUTPUT_SCHEMA_VALIDATION_FAILED = "OUTPUT_SCHEMA_VALIDATION_FAILED"
DECISION_LOG_WRITE_FAILED = "DECISION_LOG_WRITE_FAILED"
CONSTRUCTION_SUCCESS = "CONSTRUCTION_SUCCESS"

DEFAULT_MIN_OPEN_INTEREST = 500
DEFAULT_MIN_VOLUME = 100
DEFAULT_MAX_BID_ASK_SPREAD_PCT = 0.15
DEFAULT_LIVE_FRESHNESS_SECONDS = 300
