SPEC_VERSION = "strategy-engine-v2.0"

LABEL_UP = "UP"
LABEL_FLAT = "FLAT"
LABEL_DOWN = "DOWN"

STATE_CLASSIFIABLE = "CLASSIFIABLE"

REGIME_BULLISH = "BULLISH"
REGIME_BEARISH = "BEARISH"
REGIME_FLAT = "FLAT"

FAMILY_BULL_CALL_SPREAD = "BULL_CALL_SPREAD"
FAMILY_BEAR_PUT_SPREAD = "BEAR_PUT_SPREAD"
FAMILY_BULL_PUT_SPREAD = "BULL_PUT_SPREAD"
FAMILY_BEAR_CALL_SPREAD = "BEAR_CALL_SPREAD"
FAMILY_IRON_CONDOR = "IRON_CONDOR"

CONTRACT_NEAR_MONTH = "NEAR_MONTH"
CONTRACT_NEXT_MONTH = "NEXT_MONTH"

TRANSITION_STABLE = "stable"
TRANSITION_STABLE_INITIAL = "stable_initial"
TRANSITION_PENDING_ACTIVATION = "pending_activation"
TRANSITION_PENDING_UPGRADE = "pending_upgrade"
TRANSITION_PENDING_SWITCH = "pending_switch"
TRANSITION_FORCED_INTERMEDIATE = "forced_intermediate"
TRANSITION_FAST_TRACK = "fast_track"

STRONG_BULL_SCORE = 40
STRONG_BEAR_SCORE = -40
MILD_BULL_LOWER = 10
MILD_BEAR_UPPER = -10
HIGH_CONFIDENCE = 0.60
MODERATE_CONFIDENCE = 0.45
MIN_TOPN_STRENGTH = 60
FAST_TRACK_STRENGTH = 80
MAX_SIGN_FLIPS_CONDOR = 1
MIN_DTE_ANY = 3
DEBIT_PREFERRED_NEAR_DTE = 7
CREDIT_PREFERRED_NEAR_DTE = 9
CONDOR_PREFERRED_NEAR_DTE = 12
NEXT_MONTH_MIN_DTE = 15

SUPPORTED_FAMILIES = [
    FAMILY_BULL_CALL_SPREAD,
    FAMILY_BEAR_PUT_SPREAD,
    FAMILY_BULL_PUT_SPREAD,
    FAMILY_BEAR_CALL_SPREAD,
    FAMILY_IRON_CONDOR,
]

TRANSITION_ENUM = [
    TRANSITION_STABLE,
    TRANSITION_STABLE_INITIAL,
    TRANSITION_PENDING_ACTIVATION,
    TRANSITION_PENDING_UPGRADE,
    TRANSITION_PENDING_SWITCH,
    TRANSITION_FORCED_INTERMEDIATE,
    TRANSITION_FAST_TRACK,
]

REASON_GATE_UPSTREAM_UNCLASSIFIABLE = "GATE_UPSTREAM_UNCLASSIFIABLE"
REASON_GATE_MISSING_REQUIRED_FIELD = "GATE_MISSING_REQUIRED_FIELD"
REASON_GATE_INVALID_NUMERIC = "GATE_INVALID_NUMERIC"
REASON_GATE_INSUFFICIENT_HISTORY = "GATE_INSUFFICIENT_HISTORY"
REASON_GATE_INVALID_DTE = "GATE_INVALID_DTE"
REASON_GATE_NOT_IN_UNIVERSE = "GATE_NOT_IN_UNIVERSE"

REASON_RULE_STRONG_BULLISH_DIRECTIONAL = "RULE_STRONG_BULLISH_DIRECTIONAL"
REASON_RULE_STRONG_BEARISH_DIRECTIONAL = "RULE_STRONG_BEARISH_DIRECTIONAL"
REASON_RULE_MANDATORY_BULLISH_FALLBACK = "RULE_MANDATORY_BULLISH_FALLBACK"
REASON_RULE_MANDATORY_BEARISH_FALLBACK = "RULE_MANDATORY_BEARISH_FALLBACK"
REASON_RULE_MANDATORY_FLAT_MAPPING = "RULE_MANDATORY_FLAT_MAPPING"

REASON_CONTRACT_NEAR_MONTH_DTE = "CONTRACT_NEAR_MONTH_DTE"
REASON_CONTRACT_NEXT_MONTH_DTE = "CONTRACT_NEXT_MONTH_DTE"

REASON_TRANSITION_PENDING_ACTIVATION = "TRANSITION_PENDING_ACTIVATION"
REASON_TRANSITION_PENDING_UPGRADE = "TRANSITION_PENDING_UPGRADE"
REASON_TRANSITION_PENDING_SWITCH = "TRANSITION_PENDING_SWITCH"
REASON_TRANSITION_FORCED_INTERMEDIATE = "TRANSITION_FORCED_INTERMEDIATE"
REASON_TRANSITION_INITIAL = "TRANSITION_INITIAL"
REASON_TRANSITION_FAST_TRACK = "TRANSITION_FAST_TRACK"
REASON_TRANSITION_STABLE = "TRANSITION_STABLE"

REASON_STRENGTH_ABOVE_TOPN_MIN = "STRENGTH_ABOVE_TOPN_MIN"
REASON_STRENGTH_BELOW_TOPN_MIN = "STRENGTH_BELOW_TOPN_MIN"

REASON_RUNTIME_SCHEMA_VALIDATION_FAILED = "RUNTIME_SCHEMA_VALIDATION_FAILED"
REASON_RUNTIME_STATE_PERSIST_FAILED = "RUNTIME_STATE_PERSIST_FAILED"
REASON_RUNTIME_LOG_WRITE_FAILED = "RUNTIME_LOG_WRITE_FAILED"
REASON_RUNTIME_PREVIOUS_STATE_LOCK_FAILED = "RUNTIME_PREVIOUS_STATE_LOCK_FAILED"
