"""Locked constants and enums for Strategy Engine v1.2."""
from __future__ import annotations

SPEC_VERSION = "strategy-engine-v1.2"

STRATEGY_FAMILIES = {
    "BULL_CALL_SPREAD",
    "BEAR_PUT_SPREAD",
    "BULL_PUT_SPREAD",
    "BEAR_CALL_SPREAD",
    "IRON_CONDOR",
    "NO_TRADE",
}

CONTRACT_MONTHS = {"NEAR_MONTH", "NEXT_MONTH", "NO_CONTRACT_MONTH"}

TRANSITION_STATES = {
    "stable",
    "stable_initial",
    "pending_activation",
    "pending_upgrade",
    "pending_switch",
    "forced_no_trade",
    "fast_track",
}

UPSTREAM_LABELS = {"UP", "FLAT", "DOWN"}
UPSTREAM_STATES = {"CLASSIFIABLE", "UNCLASSIFIABLE"}

STRONG_BULL_SCORE = 40
STRONG_BEAR_SCORE = -40
MILD_BULL_LOWER = 10
MILD_BULL_UPPER = 40
MILD_BEAR_LOWER = -40
MILD_BEAR_UPPER = -10
CONDOR_BALANCE_MAX = 10
HIGH_CONFIDENCE = 0.60
MODERATE_CONFIDENCE = 0.45
CONDOR_CONFIDENCE = 0.50
MIN_TOPN_STRENGTH = 60
FAST_TRACK_STRENGTH = 80
MAX_SIGN_FLIPS_CONDOR = 1

MIN_DTE_ANY = 3
FORCE_NO_TRADE_CLOSEOUT = 1
DEBIT_MIN_NEAR_DTE = 7
CREDIT_MIN_NEAR_DTE = 9
CONDOR_MIN_NEAR_DTE = 12
NEXT_MONTH_MIN_DTE = 15
FORCE_NEXT_BUFFER = 2

REASON_CODES = {
    "GATE_UPSTREAM_UNCLASSIFIABLE",
    "GATE_MISSING_REQUIRED_FIELD",
    "GATE_INVALID_NUMERIC",
    "GATE_INSUFFICIENT_HISTORY",
    "GATE_INVALID_DTE",
    "GATE_NEXT_MONTH_UNAVAILABLE",
    "GATE_NOT_IN_UNIVERSE",
    "RULE_STRONG_BULLISH_DIRECTIONAL",
    "RULE_STRONG_BEARISH_DIRECTIONAL",
    "RULE_TRUE_RANGE_PREMIUM_SELL",
    "RULE_MILD_BULLISH_CREDIT",
    "RULE_MILD_BEARISH_CREDIT",
    "RULE_NO_TRADE_DEFAULT",
    "CONTRACT_NEAR_MONTH_DTE",
    "CONTRACT_NEXT_MONTH_DTE",
    "TRANSITION_PENDING_ACTIVATION",
    "TRANSITION_PENDING_UPGRADE",
    "TRANSITION_PENDING_SWITCH",
    "TRANSITION_FORCED_NO_TRADE",
    "TRANSITION_INITIAL",
    "TRANSITION_FAST_TRACK",
    "TRANSITION_STABLE",
    "STRENGTH_ABOVE_TOPN_MIN",
    "STRENGTH_BELOW_TOPN_MIN",
    "RUNTIME_SCHEMA_VALIDATION_FAILED",
    "RUNTIME_STATE_PERSIST_FAILED",
    "RUNTIME_LOG_WRITE_FAILED",
    "RUNTIME_PREVIOUS_STATE_LOCK_FAILED",
}
